### ISSUE TITLE
Dynamic pointer adresses

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/mini-wasm#10]
Currently a pointer's address is fixed to the incrementing heap offset at compile time. Thus we are only able to change the *pointed* address at runtime, but not the *pointer's address* itself.

This pseudo code currently fails:
````c
i32 *ptrA = 0x4; // '0
i32 *ptrB = 0x8; // '4
ptrA = ptrB; // ptrA = '4
*ptrA, *ptrB // correct address resolving
ptrA == ptrB // incorrect, ptrA='0, ptrB='4
````

**Comment by PierreRossouw** [comment]
I don't fully understand the problem so I could be way off here but I don't think you can make this work without using the WASM Memory Section which is basically the Heap. You'll need to use the Linear Memory Accesses operators to implement pointers.

At least I think so?

**Comment by maierfelix** [comment]
Exactly, I'm already storing variables inside memory as soon as they are pointers and/or get traced inside the code by the address-of operator. I fixed the issue now by adding another 4 bytes to the beginning of each pointer. The first part defines the pointers own (fake) address, the second part holds the actual pointed address value. This way pointers still have the connection to the local stack but can behave like they would have real addresses. So now it's possible to change a pointer's address manually. However I'm still not sure if this fixes all C-like expectations.

**Comment by maierfelix** [comment]
I think it's fixed now - all tests are green expect the very last one (which is just a parsing issue).
