### ISSUE TITLE
Writing into memory

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/mini-wasm#3]
Something goes very wrong as soon as we try to store something in memory (no problem when reading from it though)

**Comment by PierreRossouw** [comment]
Can you elaborate? I might be able to help :)

**Comment by maierfelix** [comment]
Hi there,

the current problem is that as soon as I try to store something I get:
``failed:Result = i32.store found empty stack``

**Comment by maierfelix** [comment]
Okay, I figured out what the problem was - I just encoded the store operation incorrectly
