### ISSUE TITLE
Doesn't work in Firefox.

### ISSUE THREAD

**Issue by Jexell** [maierfelix/mini-wasm#5]
When browsing [http://maierfelix.github.io/mini-wasm/](http://maierfelix.github.io/mini-wasm/) in Firefox nothing appears to happens when I click compile. Both upon loading the page and upon clicking compile, the following is posted in the web console:
>Error: Unknown node kind undefined
>>error    http://www.felixmaier.info/mini-wasm/:58:19
>>emitNode    http://www.felixmaier.info/mini-wasm/src/emit.js:260:5
>>emitNode    http://www.felixmaier.info/mini-wasm/src/emit.js:164:5
>>emitNode/<    http://www.felixmaier.info/mini-wasm/src/emit.js:226:35
>>map    self-hosted:275:17
>>emitNode    http://www.felixmaier.info/mini-wasm/src/emit.js:226:5
>>emitFunction/<    http://www.felixmaier.info/mini-wasm/src/emit.js:304:33
>>map    self-hosted:275:17
>>emitFunction    http://www.felixmaier.info/mini-wasm/src/emit.js:304:3
>>emitNode    http://www.felixmaier.info/mini-wasm/src/emit.js:156:5
>>emitCodeSection/<    http://www.felixmaier.info/mini-wasm/src/emit.js:135:7
>>map    self-hosted:275:17
>>emitCodeSection    http://www.felixmaier.info/mini-wasm/src/emit.js:133:3
>>emit    http://www.felixmaier.info/mini-wasm/src/emit.js:47:3
>>compile    http://www.felixmaier.info/mini-wasm/src/index.js:28:3
>>cmp.onclick    http://www.felixmaier.info/mini-wasm/:56:25
>>\<anonymous\>    http://www.felixmaier.info/mini-wasm/:44:9

**Comment by f5io** [comment]
Same in chrome on osx here

**Comment by maierfelix** [comment]
Fixed, thanks for reporting
